#pragma once
#define NUM_PLAYERS 1
enum User_Movement {
		FORWARD=0,
		BACKWARD=180,
		LEFT=-90,
		RIGHT=90,
		FORWARD_LEFT=-45,
		FORWARD_RIGHT=45,
		BACKWARD_LEFT=-135,
		BACKWARD_RIGHT=135,
		NONE
};

enum Game_State {INIT, MANOTAUR_WIN, CIVILIAN_WIN, PLAYING}; 

//Networking enums
enum Opcode {INIT,JOINID, CHAT , T1, T2, CGTA, SGTR, ERROR};